#!/usr/bin/env Rscript
# ==============================================================
# Script: 12_plot_fstmap.R
# Author: Tabea Dittmar
# Year:   2025
#
# Description:
#   Read pairwise FST tables and plot an upper-triangle heatmap with
#   per-cell FST labels. Prefers the bootstrapped file with CIs, and
#   falls back to the summary if CIs are not available.
#
# Inputs (generated by 12_diversity_stats.sh / 12_fst_bootstrap.sh):
#   - 04-results/fst_pairwise_with_CI_<case>.tsv  
#       columns: pop1 pop2 mean_FST CI95_low CI95_high n_sites_boot
#   - 04-results/fst_pairwise_summary_<case>.tsv
#       columns: pop1 pop2 <fst_value_column>
#
# Outputs:
#   - 04-results/fst_heatmap_<case>.svg
#
# Usage:
#   Rscript 00-scripts/12_plot_fstmap.R allGroups
#   Rscript 00-scripts/12_plot_fstmap.R scaniaSplit
# ==============================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(svglite)
})

# USER INPUT
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 1) {
  stop("Usage: Rscript 00-scripts/14_plot_fst_heatmap.R <case>\n",
       "  <case> should match: allGroups | scaniaSplit", call. = FALSE)
}
case <- args[[1]]

rdir <- "04-results"
in_ci  <- file.path(rdir, sprintf("fst_pairwise_with_CI_%s.tsv", case))
in_sum <- file.path(rdir, sprintf("fst_pairwise_summary_%s.tsv", case))
out_svg <- file.path(rdir, sprintf("fst_heatmap_%s.svg", case))

if (file.exists(in_ci)) {
  df_in <- read.delim(in_ci, stringsAsFactors = FALSE, check.names = FALSE)
  # standardize column names
  if (!all(c("pop1","pop2","mean_FST") %in% names(df_in))) {
    stop("Input file lacks required columns: pop1, pop2, mean_FST")
  }
  df_in <- df_in %>% transmute(pop1, pop2, FST = as.numeric(mean_FST))
} else if (file.exists(in_sum)) {
  df_in <- read.delim(in_sum, stringsAsFactors = FALSE, check.names = FALSE)
  # try common column names
  val_col <- dplyr::case_when(
    "FST"       %in% names(df_in) ~ "FST",
    "fst"       %in% names(df_in) ~ "fst",
    "value"     %in% names(df_in) ~ "value",
    TRUE ~ NA_character_
  )
  if (is.na(val_col) || !all(c("pop1","pop2") %in% names(df_in))) {
    stop("Could not detect FST value column in summary. Expect columns: pop1, pop2, FST")
  }
  df_in <- df_in %>% transmute(pop1, pop2, FST = as.numeric(.data[[val_col]]))
} else {
  stop("No input file found in 04-results/ for case '", case, "'.\n",
       "Expected one of:\n - ", basename(in_ci), "\n - ", basename(in_sum))
}

# Group order
group_order <- c("Western","Central","Balkan","Baltic","Scania")


# Build symmetric matrix
# gather all group names
groups <- sort(unique(c(df_in$pop1, df_in$pop2)))
if (!is.null(group_order)) {
  # keep only those present; append any missing at the end
  groups <- unique(c(group_order[group_order %in% groups],
                     setdiff(groups, group_order)))
}

# make symmetric by stacking (pop1,pop2) and (pop2,pop1)
fst_sym <- bind_rows(
  df_in %>% select(pop1, pop2, FST),
  df_in %>% select(pop1 = pop2, pop2 = pop1, FST)
)

# full grid and upper-triangle masking
grid <- expand.grid(pop1 = groups, pop2 = groups, stringsAsFactors = FALSE) %>%
  as_tibble() %>%
  left_join(fst_sym, by = c("pop1","pop2"))

grid <- grid %>%
  mutate(ix = match(pop1, groups),
         iy = match(pop2, groups)) %>%
  mutate(FST = if_else(ix >= iy, NA_real_, FST))

# factors for plotting order: x left→right, y top→bottom (reverse)
grid <- grid %>%
  mutate(pop1 = factor(pop1, levels = groups),
         pop2 = factor(pop2, levels = rev(groups)))

# Colour scale
# Nice blue-green-yellow-white scale (low FST light, high FST darker)
fill_scale <- scale_fill_gradientn(
  name = "FST",
  colours = c("#ffffff","#fde725","#5ec962","#21918c","#3b528b"),
  na.value = "white",
  limits = c(0, max(grid$FST, na.rm = TRUE))
)

# PLOT
p <- ggplot(grid, aes(pop1, pop2, fill = FST)) +
  geom_tile() +
  geom_text(data = subset(grid, !is.na(FST)),
            aes(label = sprintf("%.3f", FST)), size = 3.3) +
  fill_scale +
  coord_equal() +
  labs(x = NULL, y = NULL) +
  theme_minimal(base_size = 13) +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.grid  = element_blank(),
    legend.title = element_text(size = 11),
    legend.text  = element_text(size = 10),
    plot.margin  = margin(10, 12, 10, 12)
  )

ggsave(out_svg, p, width = 7.5, height = 6.0, dpi = 300)
message("Saved: ", out_svg)
